import { ArrowRight, CheckCircle2, CircleAlert, Filter, GitBranch, Info, Play, RefreshCw, Search, SlidersHorizontal, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { type ReactNode, useMemo, useState } from "react";
import { Link } from "wouter";
import { PageHeader, SectionLabel } from "@/components/quality-shell";
import { batches, binomialAtLeast, binomialCdf, binomialProbability, formatNumber, formatPct, highestRateBatch, lowestRateBatch, observedMean, overallDefectRate, seededSimulation, totalDefective, totalInspected } from "@/lib/stats";

function ShellPage({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`mx-auto w-full max-w-[1400px] px-5 py-9 sm:px-8 lg:px-12 lg:py-12 ${className}`}>{children}</div>;
}

function Metric({ label, value, note, accent = false, testId }: { label: string; value: string; note: string; accent?: boolean; testId: string }) {
  return <div className={`metric-card p-5 ${accent ? "border-primary/40 bg-primary text-primary-foreground" : ""}`} data-testid={`metric-${testId}`}><div className={`lab-mono text-[10px] uppercase tracking-[.12em] ${accent ? "text-primary-foreground/60" : "text-muted-foreground"}`}>{label}</div><div className="lab-display mt-3 text-3xl font-semibold">{value}</div><div className={`mt-2 text-[11px] ${accent ? "text-primary-foreground/65" : "text-muted-foreground"}`}>{note}</div></div>;
}

function EmptyState({ message }: { message: string }) {
  return <div className="rounded-xl border border-dashed border-border bg-card px-6 py-14 text-center" data-testid="empty-filter-results"><CircleAlert className="mx-auto text-muted-foreground" size={22} /><p className="mt-3 text-sm font-semibold">No batches match this view</p><p className="mt-1 text-xs text-muted-foreground">{message}</p></div>;
}

export function OverviewPage() {
  return <ShellPage>
    <PageHeader eyebrow="Project overview · 01" title={<>When variation becomes a <span className="text-primary">real risk.</span></>} description="A transparent, local notebook for tracing manufacturing variation from inspected units to the probability of a defect in the next product." action={<Link href="/dataset" className="btn-primary" data-testid="link-start-investigation">Open the dataset <ArrowRight size={16} /></Link>} />
    <div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]">
      <section className="grid-paper relative overflow-hidden rounded-2xl border border-border bg-card p-7 sm:p-10" data-testid="section-project-summary">
        <div className="absolute right-8 top-8 hidden h-24 w-24 rounded-full border border-primary/20 sm:block" /><div className="absolute right-[68px] top-[68px] hidden h-4 w-4 rounded-full bg-accent sm:block" />
        <div className="eyebrow">THE QUESTION</div>
        <h2 className="lab-display mt-5 max-w-xl text-3xl font-semibold leading-tight sm:text-4xl">How consistently does our line make a good product?</h2>
        <p className="mt-5 max-w-2xl text-sm leading-7 text-muted-foreground">We treat each inspected product as a trial: it either passes or becomes a defect. The batch record gives us an observed defect rate; the binomial model turns that rate into a forecast we can reason about.</p>
        <div className="mt-9 grid max-w-xl grid-cols-2 gap-x-8 gap-y-5 border-t border-border pt-6 sm:grid-cols-4">
          <div><div className="lab-mono text-xl font-medium text-primary">{formatNumber(totalInspected)}</div><div className="mt-1 text-[11px] text-muted-foreground">units inspected</div></div>
          <div><div className="lab-mono text-xl font-medium text-primary">{formatNumber(totalDefective)}</div><div className="mt-1 text-[11px] text-muted-foreground">defects found</div></div>
          <div><div className="lab-mono text-xl font-medium text-primary">{batches.length}</div><div className="mt-1 text-[11px] text-muted-foreground">production batches</div></div>
          <div><div className="lab-mono text-xl font-medium text-primary">{formatPct(overallDefectRate)}</div><div className="mt-1 text-[11px] text-muted-foreground">overall rate</div></div>
        </div>
      </section>
      <section className="metric-card flex flex-col justify-between p-7" data-testid="section-why-probability">
        <div><div className="eyebrow">WHY IT MATTERS</div><h2 className="lab-display mt-4 text-3xl font-semibold">A percentage is a starting point, not a prediction.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">At scale, even a small rate can mean a meaningful number of defects. Probability helps decide whether a result is ordinary variation or a signal worth investigating.</p></div>
        <Link href="/binomial-calculator" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-primary" data-testid="link-try-calculator">Try a scenario <ArrowRight size={15} /></Link>
      </section>
    </div>
    <div className="mt-14"><SectionLabel>Project objectives</SectionLabel><div className="grid gap-3 sm:grid-cols-3">
      {[["01", "Describe the line", "Summarise the inspected batches and measure the variation between them."], ["02", "Model a defect", "Use the binomial distribution to estimate exact, upper-tail, and lower-tail outcomes."], ["03", "Make it readable", "Translate each calculation into a sentence a project reviewer can check."]].map(([number, title, copy]) => <div key={number} className="border-l-2 border-primary/30 px-5 py-2" data-testid={`objective-${number}`}><div className="lab-mono text-xs text-accent">{number}</div><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}
    </div></div>
    <div className="mt-14 flex flex-col gap-5 rounded-2xl bg-secondary p-7 sm:flex-row sm:items-center sm:justify-between sm:p-9"><div><div className="eyebrow text-primary">A GUIDED WALKTHROUGH</div><h2 className="lab-display mt-3 text-2xl font-semibold">Start with what the batches actually tell us.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Filter the records, inspect the rate, then test a probability claim in the lab.</p></div><Link href="/dataset" className="btn-primary shrink-0" data-testid="link-explore-batches">Explore batches <ArrowRight size={16} /></Link></div>
  </ShellPage>;
}

export function DatasetPage() {
  const [query, setQuery] = useState("");
  const [sortBy, setSortBy] = useState<"batchId" | "productsInspected" | "defectiveProducts" | "defectRate">("batchId");
  const [direction, setDirection] = useState<"asc" | "desc">("asc");
  const [threshold, setThreshold] = useState("all");
  const filtered = useMemo(() => batches.filter((batch) => {
    const queryMatch = batch.batchId.toLowerCase().includes(query.toLowerCase().trim());
    const thresholdMatch = threshold === "all" || (threshold === "low" ? batch.defectRate < overallDefectRate : threshold === "watch" ? batch.defectRate >= overallDefectRate : batch.defectRate > overallDefectRate * 1.35);
    return queryMatch && thresholdMatch;
  }).sort((a, b) => {
    const left = a[sortBy]; const right = b[sortBy];
    const result = typeof left === "string" ? left.localeCompare(right as string) : (left as number) - (right as number);
    return direction === "asc" ? result : -result;
  }), [query, sortBy, direction, threshold]);
  const changeSort = (value: typeof sortBy) => { if (value === sortBy) setDirection(direction === "asc" ? "desc" : "asc"); else { setSortBy(value); setDirection("asc"); } };
  return <ShellPage>
    <PageHeader eyebrow="Investigation · 02" title="Manufacturing dataset" description="Twelve production snapshots generated for this study. Search by batch, focus the rate band, or sort a column to see how the line moves." action={<div className="hidden items-center gap-2 text-xs text-muted-foreground sm:flex"><span className="status-dot" /> deterministic local data</div>} />
    <div className="grid gap-3 sm:grid-cols-[1fr_190px] lg:grid-cols-[1fr_220px_170px]">
      <label className="relative block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16} /><input type="search" className="input-lab pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search batch ID" data-testid="input-dataset-search" /></label>
      <label className="relative block"><Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={15} /><select className="input-lab pl-10" value={threshold} onChange={(event) => setThreshold(event.target.value)} data-testid="select-rate-filter"><option value="all">All rate bands</option><option value="low">Below overall</option><option value="watch">At or above overall</option><option value="high">Higher variation</option></select></label>
      <button type="button" className="btn-secondary" onClick={() => { setQuery(""); setThreshold("all"); setDirection("asc"); }} data-testid="button-reset-dataset"><RefreshCw size={15} /> Reset view</button>
    </div>
    <div className="mt-6 flex items-center justify-between"><div className="lab-mono text-[11px] text-muted-foreground" data-testid="text-filter-count">SHOWING {filtered.length} / {batches.length} BATCHES</div><div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><SlidersHorizontal size={14} /> Click a header to sort</div></div>
    <div className="table-wrap mt-3" data-testid="table-dataset"><table className="data-table"><thead><tr>{[["batchId", "Batch ID"], ["productsInspected", "Products inspected"], ["defectiveProducts", "Defective products"], ["defectRate", "Defect rate"]].map(([key, label]) => <th key={key}><button type="button" className="flex items-center gap-2 hover:text-foreground" onClick={() => changeSort(key as typeof sortBy)} data-testid={`button-sort-${key}`}>{label}{sortBy === key && <span className="text-primary">{direction === "asc" ? "↑" : "↓"}</span>}</button></th>)}<th>Reading</th></tr></thead><tbody>{filtered.map((batch) => <tr key={batch.batchId} data-testid={`row-batch-${batch.batchId}`}><td className="lab-mono font-medium text-primary">{batch.batchId}</td><td className="lab-mono">{formatNumber(batch.productsInspected)}</td><td className="lab-mono">{batch.defectiveProducts}</td><td><div className="flex items-center gap-3"><span className="lab-mono w-14">{formatPct(batch.defectRate)}</span><div className="bar-track hidden w-20 sm:block"><div className={`bar-fill ${batch.defectRate > overallDefectRate * 1.35 ? "bar-fill-warm" : ""}`} style={{ width: `${Math.min(100, batch.defectRate * 1000)}%` }} /></div></div></td><td><span className={`text-xs font-semibold ${batch.defectRate > overallDefectRate * 1.35 ? "text-accent" : "text-muted-foreground"}`}>{batch.defectRate > overallDefectRate * 1.35 ? "watch" : "in range"}</span></td></tr>)}</tbody></table></div>
    {filtered.length === 0 && <div className="mt-4"><EmptyState message="Try a batch ID like B-2407 or reset the rate band." /></div>}
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Total inspected" value={formatNumber(totalInspected)} note="across all 12 batches" testId="dataset-inspected" /><Metric label="Total defects" value={formatNumber(totalDefective)} note="observed non-conforming units" testId="dataset-defects" /><Metric label="Overall rate" value={formatPct(overallDefectRate)} note="weighted, not an average of rates" accent testId="dataset-rate" /></div>
  </ShellPage>;
}

export function DefectRatePage() {
  const sorted = [...batches].sort((a, b) => b.defectRate - a.defectRate);
  return <ShellPage>
    <PageHeader eyebrow="Investigation · 03" title="Defect rate" description="The weighted overall rate is the baseline. Each bar below shows how far a batch sits from that baseline, making variation visible before we model it." />
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Overall defect rate" value={formatPct(overallDefectRate)} note={`${totalDefective} defects / ${formatNumber(totalInspected)} inspected`} accent testId="overall-rate" /><Metric label="Highest batch" value={formatPct(highestRateBatch.defectRate)} note={`${highestRateBatch.batchId} · ${highestRateBatch.defectiveProducts} defects`} testId="highest-rate" /><Metric label="Lowest batch" value={formatPct(lowestRateBatch.defectRate)} note={`${lowestRateBatch.batchId} · ${lowestRateBatch.defectiveProducts} defects`} testId="lowest-rate" /></div>
    <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_330px]">
      <section><SectionLabel>Batch-wise defect percentages</SectionLabel><div className="space-y-4 rounded-2xl border border-border bg-card p-6 sm:p-8">{sorted.map((batch) => <div key={batch.batchId} className="grid grid-cols-[58px_1fr_60px] items-center gap-3" data-testid={`rate-row-${batch.batchId}`}><span className="lab-mono text-[11px] text-muted-foreground">{batch.batchId.slice(2)}</span><div className="bar-track h-3"><div className={`bar-fill h-3 ${batch.defectRate > overallDefectRate * 1.35 ? "bar-fill-warm" : ""}`} style={{ width: `${Math.max(3, Math.min(100, (batch.defectRate / highestRateBatch.defectRate) * 100))}%` }} /></div><span className="lab-mono text-right text-[11px]">{formatPct(batch.defectRate)}</span></div>)}<div className="mt-5 flex items-center gap-5 border-t border-border pt-5 text-[11px] text-muted-foreground"><span className="flex items-center gap-2"><span className="status-dot bg-primary" /> in range</span><span className="flex items-center gap-2"><span className="status-dot bg-accent" /> higher variation</span></div></div></section>
      <aside className="rounded-2xl bg-secondary p-7" data-testid="card-rate-readout"><div className="eyebrow">READOUT</div><h2 className="lab-display mt-4 text-2xl font-semibold">What should we notice?</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">The typical batch sits close to the overall baseline, but the spread is real: <strong className="text-foreground">{highestRateBatch.batchId}</strong> is about {((highestRateBatch.defectRate / lowestRateBatch.defectRate) - 1).toFixed(1)}× higher than <strong className="text-foreground">{lowestRateBatch.batchId}</strong>.</p><div className="mt-6 border-t border-primary/15 pt-5 text-xs leading-6 text-muted-foreground">The overall rate uses totals, so a large batch contributes more evidence than a small batch. That weighted baseline is the probability we carry into the first calculator scenario.</div><Link href="/binomial-calculator" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary" data-testid="link-rate-to-calculator">Model this rate <ArrowRight size={15} /></Link></aside>
    </div>
  </ShellPage>;
}

type Calculation = { n: number; p: number; x: number; exact: number; atMost: number; atLeast: number };
export function BinomialCalculatorPage() {
  const [n, setN] = useState(String(25));
  const [p, setP] = useState((overallDefectRate * 100).toFixed(2));
  const [x, setX] = useState("1");
  const [calculation, setCalculation] = useState<Calculation | null>(null);
  const [error, setError] = useState("");
  const calculate = () => {
    const products = Number(n); const probability = Number(p) / 100; const defective = Number(x);
    if (!Number.isInteger(products) || products < 1 || products > 5000 || probability < 0 || probability > 1 || !Number.isInteger(defective) || defective < 0 || defective > products) { setError("Use whole numbers for products and defects, and a probability from 0% to 100%."); setCalculation(null); return; }
    setError(""); setCalculation({ n: products, p: probability, x: defective, exact: binomialProbability(products, probability, defective), atMost: binomialCdf(products, probability, defective), atLeast: binomialAtLeast(products, probability, defective) });
  };
  return <ShellPage>
    <PageHeader eyebrow="Probability lab · 04" title="Binomial calculator" description="Set up one repeatable question: if each product has the same defect probability, how likely is a particular number of defects in a group?" />
    <div className="grid gap-8 lg:grid-cols-[360px_1fr]">
      <section className="rounded-2xl border border-border bg-card p-6 sm:p-7" data-testid="card-binomial-inputs"><SectionLabel>Set the trial</SectionLabel><div className="space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold">Number of products (n)</span><input type="number" min="1" max="5000" className="input-lab lab-mono" value={n} onChange={(event) => setN(event.target.value)} data-testid="input-binomial-n" /><span className="mt-1.5 block text-[11px] text-muted-foreground">How many independent products are in the group?</span></label><label className="block"><span className="mb-2 block text-xs font-bold">Probability of defect (p)</span><div className="relative"><input type="number" min="0" max="100" step="0.01" className="input-lab lab-mono pr-10" value={p} onChange={(event) => setP(event.target.value)} data-testid="input-binomial-p" /><span className="absolute right-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">%</span></div><span className="mt-1.5 block text-[11px] text-muted-foreground">Start with the weighted overall rate: {formatPct(overallDefectRate)}.</span></label><label className="block"><span className="mb-2 block text-xs font-bold">Defective products (x)</span><input type="number" min="0" className="input-lab lab-mono" value={x} onChange={(event) => setX(event.target.value)} data-testid="input-binomial-x" /><span className="mt-1.5 block text-[11px] text-muted-foreground">The outcome you want to test.</span></label>{error && <p className="rounded-lg bg-destructive/10 px-3 py-2 text-xs font-semibold text-destructive" data-testid="status-binomial-error">{error}</p>}<button type="button" className="btn-primary w-full" onClick={calculate} data-testid="button-calculate-binomial"><CalculatorIcon /> Calculate probabilities</button></div></section>
      <section className="min-w-0"><SectionLabel>Result panel</SectionLabel>{calculation ? <div className="animate-rise" data-testid="section-binomial-results"><div className="grid gap-3 sm:grid-cols-3"><Metric label={`P(X = ${calculation.x})`} value={formatPct(calculation.exact)} note="exactly this many defects" accent testId="probability-exact" /><Metric label={`P(X ≤ ${calculation.x})`} value={formatPct(calculation.atMost)} note="this many or fewer" testId="probability-at-most" /><Metric label={`P(X ≥ ${calculation.x})`} value={formatPct(calculation.atLeast)} note="this many or more" testId="probability-at-least" /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Expected defects" value={(calculation.n * calculation.p).toFixed(2)} note="mean = n × p" testId="binomial-mean" /><Metric label="Variance" value={(calculation.n * calculation.p * (1 - calculation.p)).toFixed(2)} note="spread of outcomes" testId="binomial-variance" /><Metric label="Std. deviation" value={Math.sqrt(calculation.n * calculation.p * (1 - calculation.p)).toFixed(2)} note="typical distance from mean" testId="binomial-standard-deviation" /></div><div className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-6"><div className="flex gap-3"><Info className="mt-0.5 shrink-0 text-primary" size={17} /><div><h3 className="font-bold">In normal language</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">For a group of <strong className="text-foreground">{calculation.n}</strong> products at a {formatPct(calculation.p)} defect rate, getting exactly <strong className="text-foreground">{calculation.x}</strong> defect{calculation.x === 1 ? "" : "s"} has a probability of <strong className="text-foreground">{formatPct(calculation.exact)}</strong>. The model expects about <strong className="text-foreground">{(calculation.n * calculation.p).toFixed(1)}</strong> defects per group.</p></div></div></div></div> : <div className="grid-paper flex min-h-[400px] items-center justify-center rounded-2xl border border-dashed border-border p-8 text-center" data-testid="empty-binomial-results"><div><Sparkles className="mx-auto text-accent" size={24} /><h3 className="mt-4 font-bold">Your result will appear here</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Set n, p, and x on the left, then calculate. Every value is computed locally using stable logarithmic combinations.</p></div></div>}</section>
    </div>
  </ShellPage>;
}

function CalculatorIcon() { return <span className="grid h-4 w-4 place-items-center rounded border border-current text-[9px]">=</span>; }

export function SimulationPage() {
  const [trials, setTrials] = useState("500");
  const [products, setProducts] = useState("20");
  const [probability, setProbability] = useState((overallDefectRate * 100).toFixed(2));
  const [counts, setCounts] = useState(() => seededSimulation(500, 20, overallDefectRate));
  const [runLabel, setRunLabel] = useState("500 trials · deterministic seed");
  const n = Number(products); const p = Number(probability) / 100; const t = Number(trials);
  const theoretical = Number.isInteger(n) && n > 0 && n <= 100 ? Array.from({ length: n + 1 }, (_, index) => binomialProbability(n, p, index)) : [];
  const maxCount = Math.max(...counts, 1);
  const simulatedAverage = counts.reduce((sum, count, index) => sum + count * index, 0) / Math.max(t, 1);
  const runSimulation = () => { if (Number.isInteger(t) && t >= 50 && t <= 5000 && Number.isInteger(n) && n >= 1 && n <= 100 && p >= 0 && p <= 1) { setCounts(seededSimulation(t, n, p)); setRunLabel(`${t} trials · deterministic seed`); } };
  return <ShellPage>
    <PageHeader eyebrow="Probability lab · 05" title="Simulation" description="Run the same manufacturing scenario many times. The histogram shows what happened in the sample; the line of dots shows what the binomial model expects." action={<div className="lab-mono rounded-full bg-secondary px-3 py-2 text-[10px] text-secondary-foreground" data-testid="text-simulation-seed">LOCAL / REPEATABLE</div>} />
    <div className="grid gap-8 lg:grid-cols-[260px_1fr]">
      <section className="rounded-2xl border border-border bg-card p-6" data-testid="card-simulation-controls"><SectionLabel>Simulation setup</SectionLabel><div className="space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold">Trials to run</span><input type="number" min="50" max="5000" className="input-lab lab-mono" value={trials} onChange={(event) => setTrials(event.target.value)} data-testid="input-simulation-trials" /></label><label className="block"><span className="mb-2 block text-xs font-bold">Products per trial</span><input type="number" min="1" max="100" className="input-lab lab-mono" value={products} onChange={(event) => setProducts(event.target.value)} data-testid="input-simulation-products" /></label><label className="block"><span className="mb-2 block text-xs font-bold">Defect probability</span><div className="relative"><input type="number" min="0" max="100" step=".01" className="input-lab lab-mono pr-9" value={probability} onChange={(event) => setProbability(event.target.value)} data-testid="input-simulation-probability" /><span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">%</span></div></label><button type="button" className="btn-primary mt-2 w-full" onClick={runSimulation} data-testid="button-run-simulation"><Play size={15} /> Run simulation</button><div className="border-t border-border pt-4 text-[11px] leading-5 text-muted-foreground">The seed is derived from your settings, so the same setup produces the same sample every time.</div></div></section>
      <section className="min-w-0"><SectionLabel>Observed distribution</SectionLabel><div className="rounded-2xl border border-border bg-card p-5 sm:p-8" data-testid="section-simulation-results"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="lab-display text-2xl font-semibold">Defects per {n || "—"} products</h2><p className="lab-mono mt-1 text-[10px] text-muted-foreground" data-testid="text-simulation-run-label">{runLabel}</p></div><div className="flex items-center gap-4 text-[10px] text-muted-foreground"><span className="flex items-center gap-2"><span className="status-dot bg-primary" /> sample count</span><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full border-2 border-accent" /> theory</span></div></div><div className="mt-10 flex h-[245px] items-end gap-1 border-b border-l border-border px-2 pb-0 pt-4 sm:gap-2">{counts.map((count, index) => <div key={index} className="group flex h-full flex-1 flex-col justify-end" data-testid={`bar-simulation-${index}`}><div className="relative"><div className="histogram-bar w-full" style={{ height: `${Math.max(4, (count / maxCount) * 185)}px` }} /><div className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-foreground px-2 py-1 text-[9px] text-background group-hover:block">{count} runs · {index} defects</div></div><div className="relative h-5 text-center"><span className="lab-mono text-[9px] text-muted-foreground">{index}</span>{theoretical[index] !== undefined && <span className="absolute left-1/2 top-0.5 h-2 w-2 -translate-x-1/2 rounded-full border-2 border-accent bg-card" />}</div></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Simulated average" value={simulatedAverage.toFixed(2)} note="average defects observed" testId="simulated-average" /><Metric label="Theoretical mean" value={(n * p).toFixed(2)} note="n × p" testId="theoretical-mean" /><Metric label="Most common result" value={String(counts.indexOf(Math.max(...counts)))} note="highest sample bar" accent testId="mode-result" /></div></div></section>
    </div>
  </ShellPage>;
}

export function BatchProbabilityPage() {
  const [batchId, setBatchId] = useState(batches[0].batchId);
  const [products, setProducts] = useState("25");
  const [defects, setDefects] = useState("1");
  const selected = batches.find((batch) => batch.batchId === batchId) ?? batches[0];
  const n = Number(products); const x = Number(defects);
  const valid = Number.isInteger(n) && n >= 1 && n <= 5000 && Number.isInteger(x) && x >= 0 && x <= n;
  const exact = valid ? binomialProbability(n, selected.defectRate, x) : 0;
  const atLeast = valid ? binomialAtLeast(n, selected.defectRate, x) : 0;
  return <ShellPage>
    <PageHeader eyebrow="Probability lab · 06" title="Batch probability" description="Choose one observed batch and carry its rate directly into a practical question about the next group of products." />
    <div className="grid gap-8 lg:grid-cols-[360px_1fr]">
      <section className="rounded-2xl border border-border bg-card p-6 sm:p-7" data-testid="card-batch-probability-inputs"><SectionLabel>Choose a batch</SectionLabel><label className="block"><span className="mb-2 block text-xs font-bold">Observed batch</span><select className="input-lab lab-mono" value={batchId} onChange={(event) => setBatchId(event.target.value)} data-testid="select-probability-batch">{batches.map((batch) => <option key={batch.batchId} value={batch.batchId}>{batch.batchId} · {formatPct(batch.defectRate)}</option>)}</select></label><div className="mt-5 rounded-xl bg-secondary p-4"><div className="lab-mono text-[10px] text-muted-foreground">OBSERVED RATE</div><div className="lab-display mt-2 text-3xl font-semibold text-primary" data-testid="text-selected-batch-rate">{formatPct(selected.defectRate)}</div><div className="mt-1 text-[11px] text-muted-foreground">{selected.defectiveProducts} defects in {formatNumber(selected.productsInspected)} inspected</div></div><div className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold">Products in next group</span><input type="number" min="1" max="5000" className="input-lab lab-mono" value={products} onChange={(event) => setProducts(event.target.value)} data-testid="input-batch-products" /></label><label className="block"><span className="mb-2 block text-xs font-bold">Defects to test (x)</span><input type="number" min="0" className="input-lab lab-mono" value={defects} onChange={(event) => setDefects(event.target.value)} data-testid="input-batch-defects" /></label></div></section>
      <section><SectionLabel>Scenario readout</SectionLabel><div className="rounded-2xl bg-primary p-7 text-primary-foreground sm:p-9" data-testid="section-batch-probability-results"><div className="eyebrow text-primary-foreground/60">SCENARIO / {selected.batchId}</div><h2 className="lab-display mt-4 max-w-xl text-3xl font-semibold">What are the odds of exactly {x || "0"} defect{x === 1 ? "" : "s"} in {n || "—"} products?</h2>{valid ? <><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-primary-foreground/10 p-5"><div className="lab-mono text-[10px] text-primary-foreground/60">EXACTLY {x}</div><div className="lab-display mt-2 text-4xl font-semibold" data-testid="text-batch-exact">{formatPct(exact)}</div></div><div className="rounded-xl bg-primary-foreground/10 p-5"><div className="lab-mono text-[10px] text-primary-foreground/60">AT LEAST {x}</div><div className="lab-display mt-2 text-4xl font-semibold" data-testid="text-batch-at-least">{formatPct(atLeast)}</div></div></div><p className="mt-7 max-w-2xl text-sm leading-7 text-primary-foreground/75" data-testid="text-batch-explanation">Using {selected.batchId}'s observed rate of {formatPct(selected.defectRate)}, the model says there is a <strong className="text-primary-foreground">{formatPct(exact)}</strong> chance of seeing exactly {x} defect{x === 1 ? "" : "s"} in a group of {n}. This is a forecast of a count, not a promise about any single item.</p></> : <p className="mt-8 rounded-lg bg-destructive/20 p-4 text-sm text-primary-foreground">Enter a whole number of products and choose a defect count between 0 and n.</p>}</div></section>
    </div>
  </ShellPage>;
}

export function ResultsPage() {
  const spread = highestRateBatch.defectRate - lowestRateBatch.defectRate;
  return <ShellPage>
    <PageHeader eyebrow="Wrap-up · 07" title="Results" description="The main observations from the generated production record and the probability experiments. These are the points to carry into a project review." />
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Weighted baseline" value={formatPct(overallDefectRate)} note="all units combined" accent testId="result-baseline" /><Metric label="Rate spread" value={formatPct(spread)} note="highest minus lowest" testId="result-spread" /><Metric label="Highest batch" value={highestRateBatch.batchId} note={formatPct(highestRateBatch.defectRate)} testId="result-highest" /><Metric label="Observed mean" value={formatPct(observedMean)} note="average of batch rates" testId="result-mean" /></div>
    <div className="mt-10 grid gap-4 lg:grid-cols-[1fr_1fr]">
      <section className="rounded-2xl border border-border bg-card p-7" data-testid="section-major-observations"><SectionLabel>Major observations</SectionLabel><div className="space-y-6">{[{ icon: TrendingUp, title: "The line is not perfectly uniform.", copy: `Batch rates range from ${formatPct(lowestRateBatch.defectRate)} to ${formatPct(highestRateBatch.defectRate)}. That spread is evidence of process variation, even though every batch is made by the same line.` }, { icon: GitBranch, title: "The baseline needs a definition.", copy: `The weighted rate is ${formatPct(overallDefectRate)}, while the simple average of batch rates is ${formatPct(observedMean)}. Larger batches should carry more weight when estimating the next unit.` }, { icon: TrendingDown, title: "Probability makes counts concrete.", copy: "A defect rate becomes more useful when it answers a question about a group: exactly how many, at most how many, or how many would be unusual." }].map(({ icon: Icon, title, copy }, index) => <div key={title} className="flex gap-4" data-testid={`observation-${index}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-secondary text-primary"><Icon size={17} /></span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{copy}</p></div></div>)}</div></section>
      <section className="grid-paper rounded-2xl border border-border bg-card p-7" data-testid="section-review-checklist"><SectionLabel>Review checklist</SectionLabel><div className="space-y-3">{["Dataset is deterministic and traceable by batch ID.", "Overall rate is calculated from total counts.", "Binomial probabilities use logarithmic combinations.", "Simulation can be repeated with the same inputs.", "Each result is explained in student language."].map((item, index) => <div className="flex items-start gap-3 border-b border-border/70 py-3 last:border-0" key={item} data-testid={`checklist-item-${index}`}><CheckCircle2 className="mt-0.5 shrink-0 text-primary" size={16} /><span className="text-sm leading-6">{item}</span></div>)}</div><Link href="/conclusion" className="btn-secondary mt-6 w-full" data-testid="link-results-conclusion">Read the conclusion <ArrowRight size={15} /></Link></section>
    </div>
  </ShellPage>;
}

export function ConclusionPage() {
  return <ShellPage>
    <PageHeader eyebrow="Wrap-up · 08" title="Conclusion" description="The final answer, without hiding behind notation." />
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <article className="rounded-2xl bg-primary p-8 text-primary-foreground sm:p-12" data-testid="section-conclusion-statement"><div className="eyebrow text-primary-foreground/60">THE SHORT VERSION</div><h2 className="lab-display mt-6 max-w-2xl text-4xl font-semibold leading-[1.05] sm:text-5xl">Small variation is still a quality signal.</h2><p className="mt-7 max-w-2xl text-base leading-8 text-primary-foreground/75">Across {formatNumber(totalInspected)} inspected products, we found {totalDefective} defects, giving an overall observed defect probability of {formatPct(overallDefectRate)}. Most batches sit near that baseline, but the difference between the best and highest-rate batches shows that the process has room to become more consistent.</p><p className="mt-5 max-w-2xl text-base leading-8 text-primary-foreground/75">The binomial model lets us move from “about {formatPct(overallDefectRate)} are defective” to a useful operational question: how many defects should we expect in the next {25} products, and how surprising would a particular count be? That is the bridge from descriptive statistics to quality-control action.</p></article>
      <div className="space-y-5"><section className="metric-card p-7" data-testid="card-next-step"><div className="eyebrow">NEXT STEP</div><h3 className="lab-display mt-3 text-2xl font-semibold">Use the model as an early warning.</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">A higher-than-usual run should prompt a look at machine settings, material lots, or inspection records. Probability does not name the cause; it tells us when to ask better questions.</p></section><section className="metric-card p-7" data-testid="card-model-limit"><div className="eyebrow">MODEL LIMIT</div><h3 className="lab-display mt-3 text-2xl font-semibold">The assumptions matter.</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">The binomial model assumes each product has the same probability and that product outcomes are independent. Real production can violate both assumptions, so this is a useful baseline rather than a perfect replica of the line.</p></section></div>
    </div>
    <div className="mt-8 flex flex-col items-start justify-between gap-4 border-t border-border pt-7 sm:flex-row sm:items-center"><p className="text-sm text-muted-foreground">The notebook is complete. The data, calculations, and simulation remain available to inspect.</p><Link href="/" className="btn-secondary" data-testid="link-return-overview">Return to overview <ArrowRight size={15} /></Link></div>
  </ShellPage>;
}
